import GlobalContextProvider from '~/contexts/GlobalContextProvider'
import { type Session } from 'next-auth'
import { SessionProvider } from 'next-auth/react'
import { type AppType } from 'next/app'
import { api } from '~/utils/api'
import { Toaster } from 'react-hot-toast'
import '~/styles/globals.css'
import Head from 'next/head'


const MyApp: AppType<{ session: Session | null }> = ({
  Component,
  pageProps: { session, ...pageProps },
}) => {
  return (
    <SessionProvider session={session}>
      <Toaster/> 
      <Head>
        <title>Piórem i klawiszem</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalContextProvider>
        <Component {...pageProps} />
      </GlobalContextProvider>
    </SessionProvider>
  )
}

export default api.withTRPC(MyApp)
